In [3]:
import pandas as pd
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn import svm
from sklearn.model_selection import cross_validate as cv
from sklearn.model_selection import cross_val_score
import matplotlib.pylab as plt
import warnings
from sklearn.model_selection import train_test_split


In [4]:
def get_nonstring_cols(data_cols):
	cols_to_keep=[]
	train_cols=[]
	for col in data_cols:
		if col!='URL' and col!='host' and col!='path':
			cols_to_keep.append(col)
			if col!='malicious' and col!='result':
				train_cols.append(col)
	return [cols_to_keep,train_cols]

In [5]:
def get_test_features(urls_to_test):
    features = []
    for line in urls_to_test:
        url = line.strip()
        if url != '':
            print('working on: ' + url)  # showoff
            feature = urlfeature.feature_extract(url)
            features.append(feature)
    return features

In [7]:
df=pd.read_csv('./dataset/url_features.csv')
cols_to_keep,train_cols=get_nonstring_cols(df.columns)
X=df[train_cols]
y=df['malicious']
train_cols

['token_count',
 'rank_host',
 'rank_country',
 'ASNno',
 'sec_sen_word_cnt',
 'avg_token_length',
 'No_of_dots',
 'Length_of_url',
 'avg_path_token',
 'IPaddress_presence',
 'Length_of_host',
 'safebrowsing',
 'avg_domain_token_length',
 'path_token_count',
 'largest_domain',
 'domain_token_count',
 'largest_path',
 'largest_token']

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)


In [9]:
print(len(X_train)
,len(X_test) )

581 249


In [10]:
X_test.head()

token_count  rank_host  rank_country  ASNno  sec_sen_word_cnt  \
608            6         -1            -1  22489                 0   
457            3        461             7  13335                 0   
290            3        219           113  14492                 0   
558            3        450           360  11691                 0   
168            4        120           175  38895                 0   

     avg_token_length  No_of_dots  Length_of_url  avg_path_token  \
608          5.000000           2             37             4.0   
457          4.000000           1             16             0.0   
290          7.333333           1             26             0.0   
558          5.000000           1             19             0.0   
168          4.500000           2             23             0.0   

     IPaddress_presence  Length_of_host  safebrowsing  \
608                   0              15             0   
457                   0               9             0   
290                   0              19             0   
558                   0              12             0   
168                   0              16             0   

     avg_domain_token_length  path_token_count  largest_domain  \
608                 7.000000                 3              11   
457                 4.000000                 0               5   
290                 9.000000                 0              15   
558                 5.500000                 0               8   
168                 4.666667                 0               6   

     domain_token_count  largest_path  largest_token  
608                   2             6             11  
457                   2             0              5  
290                   2             0             15  
558                   2             0              8  
168                   3             0              6

In [11]:
rf = RandomForestClassifier(n_estimators=150)
lr=LogisticRegression()

In [12]:
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=150, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [13]:
lr.fit(X_train,y_train)

D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [14]:
scores=cross_val_score(rf, X_train,y_train , cv=30)

In [15]:
lr_scores=cross_val_score(lr, X_train,y_train , cv=30)

D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to sile

D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_cl

In [10]:
'Estimated score RandomForestClassifier: %0.5f (+/- %0.5f)' % (scores.mean(), scores.std() / 2)

'Estimated score RandomForestClassifier: 0.98337 (+/- 0.01465)'

In [21]:
'Estimated score RandomForestClassifier: %0.5f (+/- %0.5f)' % (lr_scores.mean(), lr_scores.std() / 2)

'Estimated score RandomForestClassifier: 0.85738 (+/- 0.02830)'

In [16]:
y_pred=rf.predict(X_test)

In [17]:
lr.predict(X_test)

array([0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2,
       0, 0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2,
       0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0, 1, 2,
       0, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 2,
       0, 2, 2, 0, 2, 1, 2, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2, 0, 2, 0, 0, 0,
       0, 0, 2, 0, 2, 0, 0], dtype=int64)

In [12]:
test_urls=['www.family-partners.fr/data.dpg']

In [33]:
test_links_features=[
    {'safebrowsing': -1, 'token_count': 4, 'avg_path_token': 0, 'largest_path': 0, 'largest_token': 7, 'URL': 'https://www.twitter.com', 'sec_sen_word_cnt': 0, 'IPaddress_presence': 0, 'largest_domain': 7, 'No_of_dots': 2, 'host': 'www.twitter.com', 'Length_of_url': 23, 'ASNno': -1, 'rank_country': u'28', 'rank_host': u'44', 'path_token_count': 0, 'domain_token_count': 3, 'path': '', 'avg_token_length': 4.5, 'avg_domain_token_length': 4.333333333333333, 'Length_of_host': 15},
    {'safebrowsing': -1, 'token_count': 4, 'avg_path_token': 0, 'largest_path': 0, 'largest_token': 6, 'URL': 'https://www.google.com', 'sec_sen_word_cnt': 0, 'IPaddress_presence': 0, 'largest_domain': 6, 'No_of_dots': 2, 'host': 'www.google.com', 'Length_of_url': 22, 'ASNno': 15169, 'rank_country': u'1', 'rank_host': u'1', 'path_token_count': 0, 'domain_token_count': 3, 'path': '', 'avg_token_length': 4.25, 'avg_domain_token_length': 4.0, 'Length_of_host': 14}
]


In [34]:
test_df = pd.DataFrame(test_links_features)

In [35]:
x_test=test_df[train_cols]
rf.predict(x_test)

array([0, 0], dtype=int64)

In [18]:
confusion_matrix(y_test, y_pred)

array([[155,   0,   0],
       [  0,  11,   2],
       [  1,   1,  79]], dtype=int64)